### PR TITLE
Fix(run.sh): provide full repo name owner/package

### PR DESCRIPTION
**Pull request by Bad3r**
```sh
Unable to find image 'rebornos:latest' locally
docker: Error response from daemon: pull access denied for rebornos, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

To fix this error, simply add the repo owner name `rebornos/rebornos:latest` like in `build.sh`

Please update the script version on docker hub when you get a chance: https://hub.docker.com/r/rebornos/rebornos

I updated the readme.md file idk if that is reflected in Docker Hub

### CODE REVIEW

**Review by pvshvp-oss — DISMISSED** [review]

**Review by pvshvp-oss — APPROVED** [review]

**Comment by pvshvp-oss** [comment]
> Please update the script version on docker hub when you get a chance: https://hub.docker.com/r/rebornos/rebornos

Done. Thanks :)

**Comment by Bad3r** [comment]
@shivanandvp my pleasure. Thank you for creating this image. I have looked before for arch based spins docker images and seems like most projects do not provide one.

**Comment by pvshvp-oss** [comment]
> @shivanandvp my pleasure. Thank you for creating this image. I have looked before for arch based spins docker images and seems like most projects do not provide one.

This is a new project, not even half a day old. I used another docker project of mine and then copy pasted it here. I have not had enough time to iron out bugs yet.

I intend to use this docker image for Github CI workflows (like automatic building of ISOs) :)

**Comment by Bad3r** [comment]
@shivanandvp oh Awesome. Yeah, I noticed it's only few hours old xD snuck this PR before you noticed the typo xD 


I randomly came across this distro because some YouTuber made a video about it, and I was curious what makes it different, so I started looking through the repos and found this.

**Comment by Bad3r** [comment]
@shivanandvp also any reason why you reverted the full qualified name from the run.sh script? `rebornos/rebornos:latest` ⇾ `rebornos:latest`?   
This will break the run command for some users if not all, and for security it's important to specify the repo. Docker images do not have unique names.

I can fork this repo and host the image under `Bad3r/rebornos:latest` as an example

**Comment by pvshvp-oss** [comment]
> @shivanandvp also any reason why you reverted the full qualified name from the run.sh script? `rebornos/rebornos:latest` ⇾ `rebornos:latest`?  This will break the run command for some users if not all, and for security it's important to specify the repo. Docker images do not have unique names.

@Bad3r The `run.sh` file within the git repo is **_different_** from the script pasted in the README (Github, Dockerhub). 

**Regular user**s will read the description on Dockerhub or the README section on how to use the DockerHub image. This information corresponds to _Option 2_ below. This code specifies the proper unique path referring to the DockerHub image. 

**Developers** will use the `build.sh` and `run.sh` files provided for locally testing the changes they make after cloning the project. This corresponds to _Option 1_ below.

1. The `run.sh` file in the git repo is meant to run the locally built docker image (from the build.sh file). This is for developers like us who clone the git repo, modify the dockerfile and want to quickly test the local changes. 
2. This is different from the script pasted in _README_ (both Github and Dockerhub) which is meant **for users** to pull the image from dockerhub. Hope that clears the confusion. If you see, the README mentions that the code pasted is for using the DockerHub image.

**Comment by Bad3r** [comment]
Oh, I see, that makes sense. Thank you for the clarification!

**Comment by pvshvp-oss** [comment]
> @shivanandvp also any reason why you reverted the full qualified name from the run.sh script? `rebornos/rebornos:latest` ⇾ `rebornos:latest`?  This will break the run command for some users if not all, and for security it's important to specify the repo. Docker images do not have unique names.
> 
> I can fork this repo and host the image under `Bad3r/rebornos:latest` as an example

@Bad3r I think you were right and I was wrong. I will revert to what you had suggested.

My older project no longer works without the new format

**Comment by Bad3r** [comment]
@shivanandvp Thanks for letting me know. I think it was a recent change

**Pull request merged**
